name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
      with:
        node-version: '10.x'
    - name: Build and Test
      run: |
        npm install
        npm run build
        npm run test
